#!/usr/bin/env python3
"""
Enhance tools/nudge-strings.json with native titles, taglines, subtitles, badges,
and pillars for all 51 locales.
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STRINGS_PATH = os.path.join(ROOT, "tools", "nudge-strings.json")

with open(STRINGS_PATH, "r", encoding="utf-8") as f:
    L = json.load(f)

# Extended translations for all 51 languages
EXT = {
    "it": {
        "name": "Nudge — Diario e Journal Offline con Assistente IA Locale",
        "subtitle": "Diario personale offline con IA integrata per Windows",
        "tagline": "I tuoi pensieri appartengono a te — non al cloud.",
        "badge_offline": "100% Offline / Air-Gapped",
        "badge_ai": "IA sul dispositivo (Zero Cloud)",
        "badge_markdown": "File Markdown (.md)",
        "badge_telemetry": "Zero Telemetria",
        "badge_hello": "Biometria Windows Hello",
        "badge_price": "0,99 $ Acquisto Singolo",
        "cta_store": "Scarica da Microsoft Store",
        "cta_trial": "Scarica la prova gratuita di 15 giorni",
        "cta_buy": "Acquista una volta — 0,99 $ a vita",
        "cta_see": "Esplora architettura e specifiche",
        "h_pillars": "I tre pilastri inviolabili di Nudge",
        "p1_title": "Vera sovranità offline",
        "p1_desc": "La privacy totale non è marketing; è una certezza architetturale. Nudge effettua zero chiamate di rete.",
        "p2_title": "Assistente IA locale discreto",
        "p2_desc": "L'intelligenza artificiale deve servire l'introspezione umana. Nudge esegue modelli linguistici direttamente sul tuo processore.",
        "p3_title": "Metriche empatiche senza sensi di colpa",
        "p3_desc": "Nessun numero rosso punitivo: Nudge offre giorni di grazia per le serie e celebra il ritorno alla scrittura."
    },
    "nl": {
        "name": "Nudge — Offline Dagboek & Journal met Lokale AI-Metgezel",
        "subtitle": "Offline dagboek met lokale AI voor Windows",
        "tagline": "Je gedachten zijn van jou — niet van de cloud.",
        "badge_offline": "100% Offline / Air-Gapped",
        "badge_ai": "On-Device AI (Geen Cloud)",
        "badge_markdown": "Echte Markdown (.md)",
        "badge_telemetry": "Nul Telemetrie",
        "badge_hello": "Windows Hello Biometrie",
        "badge_price": "$ 0,99 Eenmalig",
        "cta_store": "Download in Microsoft Store",
        "cta_trial": "Download 15 dagen gratis proefversie",
        "cta_buy": "Eenmalig kopen — $ 0,99 voor altijd",
        "cta_see": "Bekijk architectuur & specificaties",
        "h_pillars": "De drie onwrikbare pijlers van Nudge",
        "p1_title": "Echte offline soevereiniteit",
        "p1_desc": "Volledige privacy is geen marketingbelofte, maar een architecturale wet. Nudge maakt nul netwerkverbindingen.",
        "p2_title": "Rustige lokale AI-metgezel",
        "p2_desc": "AI moet menselijke introspectie dienen. Nudge voert taalmodellen rechtstreeks uit op je eigen hardware.",
        "p3_title": "Empathische statistieken zonder schuldgevoel",
        "p3_desc": "Geen rode waarschuwingen: Nudge biedt respijtdagen voor reeksen en viert je terugkeer na een pauze."
    },
    "tr": {
        "name": "Nudge — Yerel Yapay Zekalı Çevrimdışı Günlük ve Hatıra Defteri",
        "subtitle": "Windows için Cihaz Üzerinde Yapay Zekalı Çevrimdışı Günlük",
        "tagline": "Düşünceleriniz size aittir — buluta değil.",
        "badge_offline": "%100 Çevrimdışı / Air-Gapped",
        "badge_ai": "Cihaz İçi SLM (Sıfır Bulut)",
        "badge_markdown": "Saf Markdown (.md)",
        "badge_telemetry": "Sıfır Telemetri",
        "badge_hello": "Windows Hello Biyometri",
        "badge_price": "$0.99 Tek Seferlik",
        "cta_store": "Microsoft Store'dan Edin",
        "cta_trial": "15 Günlük Ücretsiz Denemeyi İndir",
        "cta_buy": "Tek Seferde Satın Al — $0.99 Ömür Boyu",
        "cta_see": "Mimariyi ve Teknik Özellikleri Keşfet",
        "h_pillars": "Nudge'ın Değişmez Üç Temel Taşı",
        "p1_title": "Gerçek Çevrimdışı Egemenlik",
        "p1_desc": "Tam gizlilik mimari bir kuraldır. Nudge çalışma anında sıfır ağ isteği gerçekleştirir.",
        "p2_title": "Sessiz Cihaz İçi Yapay Zeka",
        "p2_desc": "Yapay zeka iç gözleme hizmet etmelidir. Nudge modelleri CPU, GPU veya NPU üzerinde yerel çalıştırır.",
        "p3_title": "Suçluluk Hissettirmeyen Metrikler",
        "p3_desc": "Kırmızı ceza sayaçları yok: Nudge serilere esnek mola günleri tanır ve geri dönüşünüzü kutlar."
    },
    "pl": {
        "name": "Nudge — Dziennik offline i pamiętnik z lokalnym asystentem AI",
        "subtitle": "Dziennik offline z lokalną sztuczną inteligencją dla Windows",
        "tagline": "Twoje myśli należą do Ciebie — nie do chmury.",
        "badge_offline": "100% Offline / Air-Gapped",
        "badge_ai": "Lokalne AI na urządzeniu (Zero Chmury)",
        "badge_markdown": "Czysty Markdown (.md)",
        "badge_telemetry": "Zero Telemetrii",
        "badge_hello": "Biometria Windows Hello",
        "badge_price": "0,99 $ Jednorazowo",
        "cta_store": "Pobierz z Microsoft Store",
        "cta_trial": "Pobierz 15-dniowy bezpłatny okres próbny",
        "cta_buy": "Kup raz — 0,99 $ na zawsze",
        "cta_see": "Poznaj architekturę i specyfikację",
        "h_pillars": "Trzy niezmienne filary Nudge",
        "p1_title": "Prawdziwa suwerenność offline",
        "p1_desc": "Prywatność to reguła architektury. Nudge wykonuje zero zapytań sieciowych.",
        "p2_title": "Dyskretny asystent AI na urządzeniu",
        "p2_desc": "Sztuczna inteligencja ma wspierać refleksję. Modele działają lokalnie na Twoim procesorze.",
        "p3_title": "Empatyczne statystyki bez poczucia winy",
        "p3_desc": "Koniec z czerwonymi karami: Nudge oferuje dni łaski i celebruje powrót do pisania."
    },
    "ko": {
        "name": "Nudge — 온디바이스 AI 동반자가 있는 오프라인 일기 및 저널",
        "subtitle": "Windows용 완전 오프라인 일기 및 온디바이스 AI 컴패니언",
        "tagline": "당신의 생각은 당신의 것 — 클라우드의 것이 아닙니다.",
        "badge_offline": "100% 완전 오프라인 / 에어갭",
        "badge_ai": "온디바이스 SLM (클라우드 제로)",
        "badge_markdown": "순수 Markdown (.md)",
        "badge_telemetry": "원격 측정 수집 제로",
        "badge_hello": "Windows Hello 생체 인식 잠금",
        "badge_price": "$0.99 1회 영구 구매",
        "cta_store": "Microsoft Store에서 다운로드",
        "cta_trial": "15일 무제한 무료 체험판 다운로드",
        "cta_buy": "평생 라이선스 — $0.99 1회 구매",
        "cta_see": "아키텍처 및 상세 사양 살펴보기",
        "h_pillars": "Nudge의 흔들리지 않는 세 가지 기둥",
        "p1_title": "진정한 오프라인 데이터 주권",
        "p1_desc": "완벽한 프라이버시는 아키텍처 불변성입니다. Nudge는 실행 중 네트워크 통신을 전혀 하지 않습니다.",
        "p2_title": "조용한 온디바이스 AI 컴패니언",
        "p2_desc": "AI는 인간의 성찰을 돕는 거울이어야 합니다. 모델을 100% 로컬로 구동합니다.",
        "p3_title": "죄책감 없는 따뜻한 통계 지표",
        "p3_desc": "빨간 숫자로 자책하게 만들지 않습니다. 관대한 유예일과 솔직한 중앙값 통계를 제공합니다."
    },
    "uk": {
        "name": "Nudge — Офлайн-щоденник та журнал із локальним ШІ-компаньйоном",
        "subtitle": "Офлайн-щоденник для Windows із локальним ШІ",
        "tagline": "Ваші думки належать вам — а не хмарі.",
        "badge_offline": "100% Офлайн / Air-Gapped",
        "badge_ai": "ШІ на пристрої (Без хмари)",
        "badge_markdown": "Чистий Markdown (.md)",
        "badge_telemetry": "Нуль телеметрії",
        "badge_hello": "Біометрія Windows Hello",
        "badge_price": "Одноразово $0.99",
        "cta_store": "Завантажити з Microsoft Store",
        "cta_trial": "15 днів безкоштовної пробної версії",
        "cta_buy": "Купити назавжди — $0.99",
        "cta_see": "Архітектура та специфікації",
        "h_pillars": "Три непорушні стовпи Nudge",
        "p1_title": "Справжній офлайн-суверенітет",
        "p1_desc": "Повна приватність — це програмний інваріант. Nudge не робить жодного мережевого запиту.",
        "p2_title": "Тихий локальний ШІ-компаньйон",
        "p2_desc": "ШІ для внутрішнього осмислення. Моделі працюють безпосередньо на вашому процесорі чи NPU.",
        "p3_title": "Турботливі метрики без почуття провини",
        "p3_desc": "Жодних червоних штрафів: Nudge враховує дні поблажки та святкує повернення до записів."
    },
    "cs": {
        "name": "Nudge — Offline deník a zápisník s lokálním AI společníkem",
        "subtitle": "Offline deník pro Windows s umělou inteligencí na zařízení",
        "tagline": "Vaše myšlenky patří vám — ne cloudu.",
        "badge_offline": "100% Offline / Air-Gapped",
        "badge_ai": "Lokální AI (Žádný cloud)",
        "badge_markdown": "Čistý Markdown (.md)",
        "badge_telemetry": "Nulová telemetrie",
        "badge_hello": "Windows Hello biometrie",
        "badge_price": "$0.99 Jednorázově",
        "cta_store": "Získat v Microsoft Store",
        "cta_trial": "Vyzkoušet na 15 dní zdarma",
        "cta_buy": "Koupit jednou — $0.99 na celý život",
        "cta_see": "Prozkoumat architekturu a parametry",
        "h_pillars": "Tři neměnné pilíře Nudge",
        "p1_title": "Skutečná offline suverenita",
        "p1_desc": "Úplné soukromí je architektonické pravidlo. Nudge neprovádí žádné síťové požadavky.",
        "p2_title": "Tichý lokální AI společník",
        "p2_desc": "AI má sloužit lidské introspekci. Jazykové modely běží přímo na vašem hardwaru.",
        "p3_title": "Laskavé metriky bez výčitek",
        "p3_desc": "Žádná červená čísla: Nudge nabízí dny tolerance a oslavuje váš návrat k psaní."
    },
    "ro": {
        "name": "Nudge — Jurnal offline cu companion AI local",
        "subtitle": "Jurnal offline pentru Windows cu inteligență artificială pe dispozitiv",
        "tagline": "Gândurile tale îți aparțin ție — nu cloud-ului.",
        "badge_offline": "100% Offline / Air-Gapped",
        "badge_ai": "IA pe dispozitiv (Zero Cloud)",
        "badge_markdown": "Markdown Pur (.md)",
        "badge_telemetry": "Zero Telemetrie",
        "badge_hello": "Biometrie Windows Hello",
        "badge_price": "0,99 $ Plată Unică",
        "cta_store": "Obține din Microsoft Store",
        "cta_trial": "Descarcă versiunea gratuită de 15 zile",
        "cta_buy": "Cumpără o dată — 0,99 $ pe viață",
        "cta_see": "Explorează arhitectura și specificațiile",
        "h_pillars": "Cei trei piloni imuabili ai Nudge",
        "p1_title": "Adevărată suveranitate offline",
        "p1_desc": "Confidențialitatea totală este o garanție arhitecturală. Nudge nu face apeluri de rețea.",
        "p2_title": "Companion IA discret pe dispozitiv",
        "p2_desc": "Inteligența artificială susține introspecția. Modelele rulează direct pe procesorul local.",
        "p3_title": "Metrici empatice fără vinovăție",
        "p3_desc": "Fără alerte roșii: Nudge oferă zile de grație și celebrează revenirea la scris."
    },
    "he": {
        "name": "Nudge — יומן אישי לא מקוון עם בינה מלאכותית מקומית",
        "subtitle": "יומן שולחני אופליין עבור Windows עם בינה מלאכותית על המכשיר",
        "tagline": "המחשבות שלך שייכות לך — לא לענן.",
        "badge_offline": "100% אופליין / מבודד רשת",
        "badge_ai": "בינה מלאכותית מקומית (אפס ענן)",
        "badge_markdown": "קובצי Markdown (.md)",
        "badge_telemetry": "אפס טלמטריה",
        "badge_hello": "נעילה ביומטרית Windows Hello",
        "badge_price": "$0.99 תשלום חד-פעמי",
        "cta_store": "הורד מחנות Microsoft",
        "cta_trial": "הורד 15 ימי ניסיון ללא הגבלה",
        "cta_buy": "קנה פעם אחת — $0.99 לכל החיים",
        "cta_see": "חקור את הארכיטקטורה והמפרט",
        "h_pillars": "שלושת עמודי התווך של Nudge",
        "p1_title": "ריבונות אופליין מלאה",
        "p1_desc": "פרטיות מלאה אינה סיסמה אלא כלל הנדסי. Nudge אינו מבצע קריאות רשת כלל.",
        "p2_title": "בינה מלאכותית שקטה ומקומית",
        "p2_desc": "ה-AI נועד לסייע להתבוננות פנימית. המודלים רצים מקומית על המעבד ללא שליחת מידע.",
        "p3_title": "מדדים רגישים ללא רגשות אשם",
        "p3_desc": "ללא מספרים אדומים מאשימים: Nudge כולל ימי חסד וחוגג חזרה לכתיבה לאחר הפסקה."
    },
    "el": {
        "name": "Nudge — Προσωπικό ημερολόγιο εκτός σύνδεσης με τοπικό AI",
        "subtitle": "Ημερολόγιο χωρίς σύνδεση για Windows με AI στη συσκευή",
        "tagline": "Οι σκέψεις σας ανήκουν σε εσάς — όχι στο cloud.",
        "badge_offline": "100% Εκτός σύνδεσης / Air-Gapped",
        "badge_ai": "Τοπικό AI στη συσκευή (Χωρίς cloud)",
        "badge_markdown": "Απλό Markdown (.md)",
        "badge_telemetry": "Μηδενική τηλεμετρία",
        "badge_hello": "Βιομετρικά Windows Hello",
        "badge_price": "0,99 $ Εφάπαξ αγορά",
        "cta_store": "Αποκτήστε το στο Microsoft Store",
        "cta_trial": "Δωρεάν δοκιμή 15 ημερών",
        "cta_buy": "Αγοράστε μία φορά — 0,99 $ για πάντα",
        "cta_see": "Αρχιτεκτονική & Προδιαγραφές",
        "h_pillars": "Οι τρεις αναλλοίωτοι πυλώνες του Nudge",
        "p1_title": "Απόλυτη κυριαρχία εκτός σύνδεσης",
        "p1_desc": "Η προστασία προσωπικών δεδομένων είναι αρχιτεκτονικός κανόνας. Μηδενικές κλήσεις δικτύου.",
        "p2_title": "Διακριτικός σύντροφος AI στη συσκευή",
        "p2_desc": "Το AI υπηρετεί την ανθρώπινη περισυλλογή. Τα μοντέλα εκτελούνται τοπικά στο υλικό σας.",
        "p3_title": "Στατιστικά με κατανόηση, χωρίς ενοχές",
        "p3_desc": "Χωρίς κόκκινες ενδείξεις ποινής: Το Nudge περιλαμβάνει ημέρες χάριτος για τις σειρές γραφής."
    },
    "hu": {
        "name": "Nudge — Offline napló és jegyzetfüzet helyi AI-társsal",
        "subtitle": "Offline asztali napló Windowsra helyi mesterséges intelligenciával",
        "tagline": "Gondolatai az önéi — nem a felhőé.",
        "badge_offline": "100% Offline / Air-Gapped",
        "badge_ai": "Helyi AI (Nulla felhő)",
        "badge_markdown": "Tiszta Markdown (.md)",
        "badge_telemetry": "Nulla telemetria",
        "badge_hello": "Windows Hello biometria",
        "badge_price": "0,99 $ Egyszeri vásárlás",
        "cta_store": "Letöltés a Microsoft Store-ból",
        "cta_trial": "15 napos ingyenes próbaverzió",
        "cta_buy": "Vásárolja meg egyszerre — 0,99 $ örökre",
        "cta_see": "Architektúra és specifikációk",
        "h_pillars": "A Nudge három megdönthetetlen pillére",
        "p1_title": "Valódi offline szuverenitás",
        "p1_desc": "A teljes adatvédelem építészeti alapelv. A Nudge nulla hálózati kérést indít.",
        "p2_title": "Csendes helyi AI-társ",
        "p2_desc": "A mesterséges intelligencia az önreflexiót szolgálja. Helyben fut a CPU-n vagy NPU-n.",
        "p3_title": "Bűntudatmentes mérőszámok",
        "p3_desc": "Nincsenek piros büntetőszámok: türelmi napok és a visszatérés ünneplése."
    },
    "da": {
        "name": "Nudge — Offline dagbog og journal med lokal AI-ledsager",
        "subtitle": "Offline dagbog til Windows med AI på enheden",
        "tagline": "Dine tanker tilhører dig — ikke skyen.",
        "badge_offline": "100% Offline / Air-Gapped",
        "badge_ai": "On-Device AI (Ingen sky)",
        "badge_markdown": "Ren Markdown (.md)",
        "badge_telemetry": "Nul telemetri",
        "badge_hello": "Windows Hello biometri",
        "badge_price": "$0.99 Engangskøb",
        "cta_store": "Hent i Microsoft Store",
        "cta_trial": "Prøv 15 dage gratis",
        "cta_buy": "Køb én gang — $0.99 for altid",
        "cta_see": "Se arkitektur og specifikationer",
        "h_pillars": "Nudges tre ufravigelige søjler",
        "p1_title": "Sand offline suverænitet",
        "p1_desc": "Komplet privatliv er et arkitektonisk krav. Nudge foretager ingen netværkskald.",
        "p2_title": "Rolig lokal AI-ledsager",
        "p2_desc": "AI skal tjene menneskelig fordybelse. Sprogmodeller kører direkte på din lokale processor.",
        "p3_title": "Empatiske målinger uden skyldfølelse",
        "p3_desc": "Ingen røde advarsler: Nudge har indbyggede nådedage for skriveserier."
    },
    "fi": {
        "name": "Nudge — Täysin offline-päiväkirja paikallisella tekoälyllä",
        "subtitle": "Offline-päiväkirja Windowsille laitteessa toimivalla tekoälyllä",
        "tagline": "Ajatuksesi kuuluvat sinulle — eivät pilveen.",
        "badge_offline": "100% Offline / Air-Gapped",
        "badge_ai": "Laitteessa toimiva AI (Ei pilveä)",
        "badge_markdown": "Puhdas Markdown (.md)",
        "badge_telemetry": "Nolla telemetriaa",
        "badge_hello": "Windows Hello -biometria",
        "badge_price": "$0.99 Kertaostos",
        "cta_store": "Hanki Microsoft Storesta",
        "cta_trial": "Lataa 15 päivän ilmainen kokeilu",
        "cta_buy": "Osta kerralla — $0.99 elinikäinen",
        "cta_see": "Tutustu arkkitehtuuriin",
        "h_pillars": "Nudgen kolme järkkymätöntä pilaria",
        "p1_title": "Aito offline-suvereniteetti",
        "p1_desc": "Täydellinen yksityisyys on arkkitehtoninen sääntö. Nudge ei tee verkkoon pyyntöjä.",
        "p2_title": "Hiljainen paikallinen tekoälykumppani",
        "p2_desc": "Tekoälyn tulee tukea itsetutkiskelua. Mallit ajetaan täysin paikallisesti laitteellasi.",
        "p3_title": "Myötätuntoiset tilastot ilman syyllisyyttä",
        "p3_desc": "Ei punaisia rangaistusnumeroita: armopäivät ja paluun arvostaminen."
    },
    "nb": {
        "name": "Nudge — Frakoblet dagbok og journal med lokal AI-ledsager",
        "subtitle": "Frakoblet dagbok for Windows med AI på enheten",
        "tagline": "Tankene dine tilhører deg — ikke skyen.",
        "badge_offline": "100% Frakoblet / Air-Gapped",
        "badge_ai": "Lokal AI på enheten (Null sky)",
        "badge_markdown": "Ren Markdown (.md)",
        "badge_telemetry": "Null telemetri",
        "badge_hello": "Windows Hello biometri",
        "badge_price": "$0.99 Engangskjøp",
        "cta_store": "Få i Microsoft Store",
        "cta_trial": "Prøv 15 dager gratis",
        "cta_buy": "Kjøp én gang — $0.99 for alltid",
        "cta_see": "Utforsk arkitektur og spesifikasjoner",
        "h_pillars": "Nudges tre urokkelige pilarer",
        "p1_title": "Ekte frakoblet suverenitet",
        "p1_desc": "Fullt personvern er et arkitektonisk krav. Nudge gjør null nettverkskall under kjøring.",
        "p2_title": "Stillegående lokal AI-ledsager",
        "p2_desc": "AI skal tjene refleksjon. Kvantiserte språkmodeller kjører direkte på din lokale maskinvare.",
        "p3_title": "Medfølende statistikk uten skam",
        "p3_desc": "Ingen røde straffetall: Nudge gir deg romslige nådedager og feirer når du gjenopptar skrivingen."
    },
    "sv": {
        "name": "Nudge — Offline-dagbok och journal med lokal AI-följeslagare",
        "subtitle": "Lokal offline-dagbok för Windows med AI på enheten",
        "tagline": "Dina tankar tillhör dig — inte molnet.",
        "badge_offline": "100% Offline / Air-Gapped",
        "badge_ai": "Lokal AI på enheten (Noll moln)",
        "badge_markdown": "Ren Markdown (.md)",
        "badge_telemetry": "Noll telemetri",
        "badge_hello": "Windows Hello biometri",
        "badge_price": "$0.99 Engångsköp",
        "cta_store": "Hämta i Microsoft Store",
        "cta_trial": "Ladda ner 15 dagars gratis provperiod",
        "cta_buy": "Köp en gång — $0.99 för alltid",
        "cta_see": "Utforska arkitektur & specifikationer",
        "h_pillars": "Nudges tre orubbliga pelare",
        "p1_title": "Sann offline-suveränitet",
        "p1_desc": "Fullständig integritet är en arkitektonisk lag. Nudge gör noll nätverksanrop vid körning.",
        "p2_title": "Tyst lokal AI-följeslagare",
        "p2_desc": "AI ska tjäna mänsklig eftertanke. Modeller körs lokalt på din CPU, GPU eller NPU.",
        "p3_title": "Medkännande statistik utan skuld",
        "p3_desc": "Inga röda straffsiffror: Nudge har inbyggda nådadagar och hyllar återkomsten efter en paus."
    },
    "vi": {
        "name": "Nudge — Nhật ký ngoại tuyến với AI đồng hành trên thiết bị",
        "subtitle": "Nhật ký ngoại tuyến dành cho Windows với AI cục bộ",
        "tagline": "Suy nghĩ của bạn thuộc về bạn — không thuộc về đám mây.",
        "badge_offline": "100% Ngoại tuyến / Không mạng",
        "badge_ai": "AI trên thiết bị (Không Cloud)",
        "badge_markdown": "Markdown thuần túy (.md)",
        "badge_telemetry": "Không thu thập dữ liệu",
        "badge_hello": "Sinh trắc học Windows Hello",
        "badge_price": "$0.99 Mua một lần",
        "cta_store": "Tải trên Microsoft Store",
        "cta_trial": "Dùng thử miễn phí 15 ngày",
        "cta_buy": "Mua một lần — $0.99 trọn đời",
        "cta_see": "Khám phá kiến trúc và thông số",
        "h_pillars": "Ba trụ cột bất biến của Nudge",
        "p1_title": "Chủ quyền ngoại tuyến thực sự",
        "p1_desc": "Bảo mật tuyệt đối là nguyên tắc cốt lõi. Nudge không thực hiện cuộc gọi mạng nào.",
        "p2_title": "AI đồng hành trên thiết bị",
        "p2_desc": "AI phục vụ cho sự suy ngẫm cá nhân, chạy 100% trên CPU, GPU hoặc NPU của máy.",
        "p3_title": "Chỉ số thấu hiểu không phán xét",
        "p3_desc": "Không có số đỏ gây áp lực: Nudge có ngày ân hạn linh hoạt và trân trọng sự trở lại viết lách."
    },
    "id": {
        "name": "Nudge — Jurnal & Buku Harian Offline dengan AI Pendamping Lokal",
        "subtitle": "Jurnal offline untuk Windows dengan AI di perangkat",
        "tagline": "Pikiran Anda adalah milik Anda — bukan milik cloud.",
        "badge_offline": "100% Offline / Air-Gapped",
        "badge_ai": "AI di Perangkat (Tanpa Cloud)",
        "badge_markdown": "Markdown Murni (.md)",
        "badge_telemetry": "Nol Telemetri",
        "badge_hello": "Biometrik Windows Hello",
        "badge_price": "$0.99 Beli Sekali",
        "cta_store": "Dapatkan di Microsoft Store",
        "cta_trial": "Unduh Uji Coba Gratis 15 Hari",
        "cta_buy": "Beli Sekali — $0.99 Seumur Hidup",
        "cta_see": "Jelajahi Arsitektur & Spesifikasi",
        "h_pillars": "Tiga Pilar Abadi Nudge",
        "p1_title": "Kedaulatan Offline Sejati",
        "p1_desc": "Privasi total adalah prinsip dasar arsitektur. Nudge tidak melakukan panggilan jaringan saat berjalan.",
        "p2_title": "AI Pendamping di Perangkat yang Tenang",
        "p2_desc": "AI harus melayani introspeksi manusia. Nudge menjalankan model bahasa langsung di CPU/GPU/NPU Anda.",
        "p3_title": "Metrik Penuh Empati Tanpa Rasa Bersalah",
        "p3_desc": "Tanpa angka merah yang menghukum: Nudge menyediakan hari toleransi untuk menjaga konsistensi Anda."
    },
    "ms": {
        "name": "Nudge — Jurnal & Diari Luar Talian dengan AI Tempatan",
        "subtitle": "Jurnal luar talian untuk Windows dengan AI pada peranti",
        "tagline": "Fikiran anda milik anda — bukan milik awan.",
        "badge_offline": "100% Luar Talian / Air-Gapped",
        "badge_ai": "AI Pada Peranti (Tanpa Awan)",
        "badge_markdown": "Markdown Tulen (.md)",
        "badge_telemetry": "Sifar Telemetri",
        "badge_hello": "Biometrik Windows Hello",
        "badge_price": "$0.99 Beli Sekali",
        "cta_store": "Dapatkan di Microsoft Store",
        "cta_trial": "Muat Turun Percubaan Percuma 15 Hari",
        "cta_buy": "Beli Sekali — $0.99 Seumur Hidup",
        "cta_see": "Terokai Seni Bina & Spesifikasi",
        "h_pillars": "Tiga Tiang Utama Nudge",
        "p1_title": "Kedaulatan Luar Talian Sebenar",
        "p1_desc": "Privasi penuh adalah jaminan seni bina. Nudge tidak membuat sebarang panggilan rangkaian semasa beroperasi.",
        "p2_title": "AI Tempatan yang Tenang",
        "p2_desc": "AI membantu refleksi diri manusia. Model dijalankan sepenuhnya secara tempatan pada perkakasan anda.",
        "p3_title": "Metrik Ihsan Tanpa Rasa Bersalah",
        "p3_desc": "Tiada penalti nombor merah: Nudge menyokong hari ihsan untuk kesinambungan penulisan anda."
    },
    "th": {
        "name": "Nudge — ไดอารี่และบันทึกประจำวันออฟไลน์พร้อม AI ประจำเครื่อง",
        "subtitle": "ไดอารี่ออฟไลน์สำหรับ Windows พร้อม AI บนอุปกรณ์ที่ไม่ต่อเน็ต",
        "tagline": "ความคิดของคุณเป็นของคุณ ไม่ใช่ของคลาวด์",
        "badge_offline": "ออฟไลน์ 100% ปลอดภัย",
        "badge_ai": "AI บนอุปกรณ์ (ไร้คลาวด์)",
        "badge_markdown": "ไฟล์ Markdown แท้ (.md)",
        "badge_telemetry": "ไร้การติดตามข้อมูล",
        "badge_hello": "ความปลอดภัย Windows Hello",
        "badge_price": "$0.99 ซื้อขาดครั้งเดียว",
        "cta_store": "รับที่ Microsoft Store",
        "cta_trial": "ดาวน์โหลดทดลองใช้ฟรี 15 วัน",
        "cta_buy": "ซื้อขาดครั้งเดียว — $0.99 ตลอดชีพ",
        "cta_see": "ดูสถาปัตยกรรมและรายละเอียด",
        "h_pillars": "สามเสาหลักที่มั่นคงของ Nudge",
        "p1_title": "อิสรภาพแห่งการออฟไลน์ที่แท้จริง",
        "p1_desc": "ความเป็นส่วนตัวคือหลักการพื้นฐาน Nudge ไม่มีการเชื่อมต่ออินเทอร์เน็ตใดๆ ขณะทำงาน",
        "p2_title": "AI ประจำเครื่องที่เงียบสงบ",
        "p2_desc": "AI เพื่อการสะท้อนตัวตน ทำงานบน CPU, GPU หรือ NPU ของคุณโดยตรง",
        "p3_title": "สถิติที่อบอุ่นไร้ความกดดัน",
        "p3_desc": "ไม่มีตัวเลขสีแดงคอยตำหนิ Nudge มีวันผ่อนปรนและร่วมยินดีเมื่อคุณกลับมาเขียนบันทึกอีกครั้ง"
    },
    "fa": {
        "name": "Nudge — دفتر خاطرات و یادداشت‌ روزانه آفلاین با هوش مصنوعی محلی",
        "subtitle": "دفترچه خاطرات آفلاین ویندوز با همراه هوش مصنوعی روی دستگاه",
        "tagline": "افکار شما متعلق به خودتان است — نه ابر.",
        "badge_offline": "۱۰۰٪ آفلاین و ایمن",
        "badge_ai": "هوش مصنوعی روی دستگاه (بدون ابر)",
        "badge_markdown": "فایل‌های متنی Markdown (.md)",
        "badge_telemetry": "بدون ردیابی داده‌ها",
        "badge_hello": "امنیت بیومتریک Windows Hello",
        "badge_price": "$0.99 خرید دائمی یک‌باره",
        "cta_store": "دریافت از Microsoft Store",
        "cta_trial": "دانلود نسخه آزمایشی رایگان ۱۵ روزه",
        "cta_buy": "خرید یک‌باره — ۲۴.۹۹ دلار برای همیشه",
        "cta_see": "مشاهده معماری و مشخصات فنی",
        "h_pillars": "سه رکن تغییرناپذیر Nudge",
        "p1_title": "حاکمیت واقعی آفلاین",
        "p1_desc": "حریم خصوصی کامل یک اصل است. Nudge هیچ ارتباط شبکه‌ای برقرار نمی‌کند.",
        "p2_title": "همراه هوش مصنوعی آرام روی دستگاه",
        "p2_desc": "هوش مصنوعی در خدمت خودآگاهی شماست و به صورت ۱۰۰٪ محلی اجرا می‌شود.",
        "p3_title": "آمارهای دلسوزانه بدون حس گناه",
        "p3_desc": "بدون ارقام قرمز سرزنش‌کننده: با روزهای مهلت انعطاف‌پذیر و بازگشت به نوشتن."
    },
    "bn": {
        "name": "Nudge — স্থানীয় AI সহ অফলাইন ডায়েরি ও জার্নাল",
        "subtitle": "উইন্ডোজের জন্য অন-ডিভাইস AI সহ অফলাইন ডায়েরি",
        "tagline": "আপনার চিন্তা আপনারই — ক্লাউডের নয়।",
        "badge_offline": "১০০% সম্পূর্ণ অফলাইন",
        "badge_ai": "অন-ডিভাইস AI (শূন্য ক্লাউড)",
        "badge_markdown": "বিশুদ্ধ Markdown (.md)",
        "badge_telemetry": "শূন্য ট্র্যাকিং",
        "badge_hello": "Windows Hello বায়োমেট্রিক্স",
        "badge_price": "$0.99 এককালীন ক্রয়",
        "cta_store": "Microsoft Store থেকে নিন",
        "cta_trial": "১৫ দিনের ফ্রি ট্রায়াল ডাউনলোড করুন",
        "cta_buy": "একবার কিনুন — $0.99 আজীবন",
        "cta_see": "আর্কিটেকচার ও স্পেসিফিকেশন দেখুন",
        "h_pillars": "Nudge-এর তিনটি অবিচল স্তম্ভ",
        "p1_title": "প্রকৃত অফলাইন সার্বভৌমত্ব",
        "p1_desc": "সম্পূর্ণ গোপনীয়তা একটি নীতি। Nudge চলার সময় কোনো নেটওয়ার্ক রিকোয়েস্ট করে না।",
        "p2_title": "শান্ত স্থানীয় AI সঙ্গী",
        "p2_desc": "AI মানুষের আত্মদর্শনের সেবায় নিয়োজিত। আপনার ডিভাইসেই মডেল সম্পূর্ণ কার্যকর হয়।",
        "p3_title": "অপরাধবোধহীন সহমর্মী মেট্রিক্স",
        "p3_desc": "কোনো লাল সতর্কবার্তা নেই: Nudge দিন বাদ গেলেও ধারাবাহিকতা রক্ষা করে।"
    },
    "yue": {
        "name": "Nudge — 離線日記本與本機 AI 伴侶",
        "subtitle": "專為 Windows 打造嘅離線日記本與端側 AI",
        "tagline": "你嘅諗法屬於你，絕對唔上雲。",
        "badge_offline": "100% 純離線運作",
        "badge_ai": "本機端側 SLM (零雲端)",
        "badge_markdown": "標準 Markdown (.md)",
        "badge_telemetry": "零資料收集",
        "badge_hello": "Windows Hello 生物辨識",
        "badge_price": "$0.99 一次買斷",
        "cta_store": "喺 Microsoft Store 下載",
        "cta_trial": "下載 15 日無限制免費試用版",
        "cta_buy": "一次買斷 — $0.99 終身使用",
        "cta_see": "探索系統架構與規格",
        "h_pillars": "Nudge 三大不可動搖基石",
        "p1_title": "真正嘅離線資料主權",
        "p1_desc": "完全私隱係設計基準。Nudge 運行時零網絡傳輸。",
        "p2_title": "克制安靜嘅本機 AI",
        "p2_desc": "AI 旨在輔助自我反思，100% 喺你嘅處理器本機運算，絕不說教。",
        "p3_title": "溫暖無負罪感嘅統計",
        "p3_desc": "冇打斷連續紀錄嘅紅字警示，給予寬限期並鼓勵隨時重拾筆墨。"
    },
    "tl": {
        "name": "Nudge — Offline Journal & Talaarawan na may AI sa Device",
        "subtitle": "Offline na journal para sa Windows na may lokal na AI",
        "tagline": "Ang iyong mga iniisip ay sa iyo — hindi sa cloud.",
        "badge_offline": "100% Offline / Ligtas",
        "badge_ai": "AI sa Device (Walang Cloud)",
        "badge_markdown": "Purong Markdown (.md)",
        "badge_telemetry": "Walang Telemetry",
        "badge_hello": "Windows Hello Biometrics",
        "badge_price": "$0.99 Isang Beses na Bili",
        "cta_store": "Kunin sa Microsoft Store",
        "cta_trial": "Mag-download ng 15-Araw na Libreng Pagsubok",
        "cta_buy": "Bumili Nang Isang Beses — $0.99 Panghabambuhay",
        "cta_see": "Tingnan ang Arkitektura at Specs",
        "h_pillars": "Tatlong Haligi ng Nudge",
        "p1_title": "Tunay na Offline na Soberanya",
        "p1_desc": "Ang kumpletong privacy ay garantisado. Walang network request ang Nudge.",
        "p2_title": "Tahimik na AI sa Device",
        "p2_desc": "Ang AI ay para sa personal na pagninilay, gumagana nang 100% sa iyong PC.",
        "p3_title": "Mabait na Sukatan Nang Walang Konsensya",
        "p3_desc": "Walang nakakatakot na pulang marka kapag may nalaktawang araw."
    },
    "te": {
        "name": "Nudge — లోకల్ AI సహచరుడితో ఆఫ్‌లైన్ డైరీ మరియు జర్నల్",
        "subtitle": "Windows కోసం పరికరంలోనే పనిచేసే AI తో కూడిన ఆఫ్‌లైన్ డైరీ",
        "tagline": "మీ ఆలోచనలు మీ స్వంతం — క్లౌడ్ కాదు.",
        "badge_offline": "100% ఆఫ్‌లైన్ భద్రత",
        "badge_ai": "పరికరంలోనే AI (క్లౌడ్ లేదు)",
        "badge_markdown": "మార్క్‌డౌన్ ఫైల్స్ (.md)",
        "badge_telemetry": "జీరో టెలిమెట్రీ",
        "badge_hello": "Windows Hello బయోమెట్రిక్స్",
        "badge_price": "$0.99 ఒకేసారి కొనుగోలు",
        "cta_store": "Microsoft Store లో పొందండి",
        "cta_trial": "15 రోజుల ఉచిత ట్రయల్ డౌన్‌లోడ్ చేయండి",
        "cta_buy": "ఒకేసారి కొనండి — $0.99 జీవితకాలం",
        "cta_see": "ఆర్కిటెక్చర్ వివరాలు చూడండి",
        "h_pillars": "Nudge యొక్క మూడు మూలస్తంభాలు",
        "p1_title": "నిజమైన ఆఫ్‌లైన్ సార్వభౌమత్వం",
        "p1_desc": "పూర్తి గోప్యత మా నిబద్ధత. Nudge ఎలాంటి ఇంటర్నెట్ కాల్స్ చేయదు.",
        "p2_title": "ప్రశాంతమైన లోకల్ AI సహచరుడు",
        "p2_desc": "AI మీ ఆత్మపరిశీలనకు తోడ్పడుతుంది. మీ పరికరంలోనే స్థానికంగా రన్ అవుతుంది.",
        "p3_title": "ఎలాంటి నేరభావన లేని సహానుభూతి గణాంకాలు",
        "p3_desc": "రోజులు తప్పిపోయినా ఎరుపు గుర్తులు ఉండవు: Nudge మీకు విశ్రాంతి రోజులను అందిస్తుంది."
    },
    "mr": {
        "name": "Nudge — स्थानिक AI सह ऑफलाइन रोजनिशी आणि डायरी",
        "subtitle": "Windows साठी ऑन-डिव्हाइस AI सह ऑफलाइन डायरी",
        "tagline": "तुमचे विचार तुमचे आहेत — क्लाउडचे नाहीत.",
        "badge_offline": "100% ऑफलाइन सुरक्षित",
        "badge_ai": "ऑन-डिव्हाइस AI (शून्य क्लाउड)",
        "badge_markdown": "मार्कडाउन फाइल्स (.md)",
        "badge_telemetry": "शून्य टेलिमेट्री",
        "badge_hello": "Windows Hello बायोमेट्रिक्स",
        "badge_price": "$0.99 एकदाच खरेदी करा",
        "cta_store": "Microsoft Store वरून मिळवा",
        "cta_trial": "15 दिवसांची मोफत चाचणी डाउनलोड करा",
        "cta_buy": "एकदाच खरेदी करा — $0.99 आजीवन",
        "cta_see": "आर्किटेक्चर आणि तपशील पहा",
        "h_pillars": "Nudge चे तीन भक्कम स्तंभ",
        "p1_title": "खरे ऑफलाइन स्वातंत्र्य",
        "p1_desc": "संपूर्ण गोपनीयता ही मूलभूत रचना आहे. Nudge कोणतेही इंटरनेट नेटवर्क वापरत नाही.",
        "p2_title": "शांत ऑन-डिव्हाइस AI साथीदार",
        "p2_desc": "AI मानवी आत्मपरीक्षणासाठी कार्य करते आणि संपूर्णपणे तुमच्या संगणकावर चालते.",
        "p3_title": "दोषमुक्त, सहानुभूतीपूर्ण आकडेवारी",
        "p3_desc": "दिवस चुकला तरी कोणतीही लाल चेतावणी नाही: Nudge पुन्हा लेखनाला सुरुवात करण्याचे कौतुक करते."
    },
    "ta": {
        "name": "Nudge — உள்ளூர் AI தோழனுடன் ஆஃப்லைன் நாட்குறிப்பு மற்றும் ஜர்னல்",
        "subtitle": "Windows க்கான சாதனத்திலுள்ள AI கொண்ட ஆஃப்லைன் நாட்குறிப்பு",
        "tagline": "உங்கள் எண்ணங்கள் உங்களுக்கே உரியவை — மேகக்கணிணிக்கு அல்ல.",
        "badge_offline": "100% ஆஃப்லைன் பாதுகாப்பு",
        "badge_ai": "சாதனத்திலுள்ள AI (கிளவுட் இல்லை)",
        "badge_markdown": "நேர்த்தியான Markdown (.md)",
        "badge_telemetry": "பூஜ்ஜிய டெலிமெטரி",
        "badge_hello": "Windows Hello பயோமெட்ரிக்ஸ்",
        "badge_price": "$0.99 ஒருமுறை வாங்குதல்",
        "cta_store": "Microsoft Store இல் பெறவும்",
        "cta_trial": "15 நாள் இலவச சோதனையைப் பதிவிறக்குக",
        "cta_buy": "ஒருமுறை வாங்கவும் — வாழ்நாள் முழுவதும் $0.99",
        "cta_see": "கட்டமைப்பு & விவரங்களை ஆராயுங்கள்",
        "h_pillars": "Nudge இன் மூன்று முக்கிய தூண்கள்",
        "p1_title": "உண்மையான ஆஃப்லைன் இறையாண்மை",
        "p1_desc": "முழுமையான தனிப்படைப்புரிமை அடிப்படை விதி. Nudge இணையப் பயன்பாட்டை நாடுவதில்லை.",
        "p2_title": "அமைதியான சாதன AI துணைவன்",
        "p2_desc": "AI உங்கள் சுய சிந்தனையை ஊக்குவிக்க சாதனத்தின் உள்ளேயே செயல்படுகிறது.",
        "p3_title": "குற்றவுணர்ச்சியற்ற கனிவான புள்ளிவிவரங்கள்",
        "p3_desc": "நாட்கள் தவறினால் சிவப்பு எச்சரிக்கைகள் இல்லை: Nudge சலுகை நாட்களை வழங்கி வரவேற்கிறது."
    },
    "gu": {
        "name": "Nudge — સ્થાનિક AI સાથી સાથે ઑફલાઇન જર્નલ અને ડાયરી",
        "subtitle": "Windows માટે ડિવાઇસ પર AI સાથે ઑફલાઇન ડાયરી",
        "tagline": "તમારા વિચારો તમારા પોતાના છે — ક્લાઉડના નથી.",
        "badge_offline": "100% ઑફલાઇન સુરક્ષિત",
        "badge_ai": "ઓન-ડિવાઇસ AI (ક્લાઉડ રહિત)",
        "badge_markdown": "શુદ્ધ Markdown (.md)",
        "badge_telemetry": "ઝીરો ટેલિમેટ્રી",
        "badge_hello": "Windows Hello બાયોમેટ્રિક્સ",
        "badge_price": "$0.99 એક વખતની ખરીદી",
        "cta_store": "Microsoft Store પરથી મેળવો",
        "cta_trial": "15 દિવસનું ફ્રી ટ્રાયલ ડાઉનલોડ કરો",
        "cta_buy": "એક વાર ખરીદો — આજીવન $0.99",
        "cta_see": "આર્કિટેક્ચર અને વિગતો જુઓ",
        "h_pillars": "Nudge ના ત્રણ અડગ સ્તંભ",
        "p1_title": "સાચી ઑફલાઇન સ્વાયત્તતા",
        "p1_desc": "સંપૂર્ણ ગોપનીયતા અમારો સિદ્ધાંત છે. Nudge ક્યારેય ઇન્ટરનેટ ડેટા મોકલતું નથી.",
        "p2_title": "શાંત ઓન-ડિવાઇસ AI સાથી",
        "p2_desc": "AI માણસના આત્મનિરીક્ષણ માટે છે અને સંપૂર્ણપણે તમારા PC પર સ્થાનિક રીતે ચાલે છે.",
        "p3_title": "દોષમુક્ત, સંવેદનશીલ આંકડાશાસ્ત્ર",
        "p3_desc": "દિવસ ચૂકી જાવ તો લાલ ચેતવણી નહીં: Nudge ગ્રેસ દિવસો આપે છે અને પરત ફરવાનું સન્માન કરે છે."
    },
    "ur": {
        "name": "Nudge — مقامی AI ساتھی کے ساتھ آف لائن ڈائری اور جرنل",
        "subtitle": "Windows کے لیے مکمل آف لائن ڈائری بمعہ ڈیوائس پر موجود AI",
        "tagline": "آپ کے خیالات آپ کے ہیں — کلاؤڈ کے نہیں۔",
        "badge_offline": "100% مکمل آف لائن",
        "badge_ai": "ڈیوائس پر AI (کلاؤڈ سے پاک)",
        "badge_markdown": "خالص مارک ڈاؤن (.md)",
        "badge_telemetry": "زیرو ٹیلی میٹری",
        "badge_hello": "Windows Hello بائیو میٹرکس",
        "badge_price": "$0.99 یکمشت خریداری",
        "cta_store": "Microsoft Store سے حاصل کریں",
        "cta_trial": "15 دن کا مفت ٹرائل ڈاؤن لوڈ کریں",
        "cta_buy": "ایک بار خریدیں — $0.99 تاحیات",
        "cta_see": "آرکیٹیکچر اور تکنیکی تفصیلات",
        "h_pillars": "Nudge کے تین بنیادی ستون",
        "p1_title": "حقیقی آف لائن خودمختاری",
        "p1_desc": "مکمل رازداری ایک بنیادی اصول ہے۔ Nudge کبھی بھی کوئی نیٹ ورک ریکویسٹ نہیں بھیجتا۔",
        "p2_title": "پرسکون ڈیوائس AI ساتھی",
        "p2_desc": "مصنوعی ذہانت انسان کی خود شناسی کے لیے ہے، جو 100% آپ کے کمپیوٹر پر چلتی ہے۔",
        "p3_title": "احساسِ ندامت سے پاک ہمدردانہ میٹرکس",
        "p3_desc": "ناغہ ہونے پر کوئی سرخ وارننگ نہیں: Nudge لچکدار رعایتی دن پیش کرتا ہے۔"
    },
    "pa": {
        "name": "Nudge — ਸਥਾਨਕ AI ਸਾਥੀ ਨਾਲ ਔਫਲਾਈਨ ਡਾਇਰੀ ਅਤੇ ਜਰਨਲ",
        "subtitle": "Windows ਲਈ ਆਨ-ਡਿਵਾਈਸ AI ਵਾਲੀ ਔਫਲਾਈਨ ਡਾਇਰੀ",
        "tagline": "ਤੁਹਾਡੇ ਵਿਚਾਰ ਤੁਹਾਡੇ ਹਨ — ਕਲਾਉਡ ਦੇ ਨਹੀਂ।",
        "badge_offline": "100% ਔਫਲਾਈਨ ਸੁਰੱਖਿਅਤ",
        "badge_ai": "ਆਨ-ਡਿਵਾਈਸ AI (ਕੋਈ ਕਲਾਉਡ ਨਹੀਂ)",
        "badge_markdown": "ਸਾਫ਼ Markdown (.md)",
        "badge_telemetry": "ਜ਼ੀਰੋ ਟੈਲੀਮੈਟਰੀ",
        "badge_hello": "Windows Hello ਬਾਇਓਮੈਟ੍ਰਿਕਸ",
        "badge_price": "$0.99 ਇੱਕ ਵਾਰ ਖਰੀਦੋ",
        "cta_store": "Microsoft Store ਤੋਂ ਲਵੋ",
        "cta_trial": "15 ਦਿਨਾਂ ਦਾ ਮੁਫ਼ਤ ਟਰਾਇਲ ਡਾਊਨਲੋਡ ਕਰੋ",
        "cta_buy": "ਇੱਕ ਵਾਰ ਖਰੀਦੋ — $0.99 ਉਮਰ ਭਰ ਲਈ",
        "cta_see": "ਆਰਕੀਟੈਕਚਰ ਅਤੇ ਵੇਰਵੇ ਵੇਖੋ",
        "h_pillars": "Nudge ਦੇ ਤਿੰਨ ਅਟੱਲ ਥੰਮ੍ਹ",
        "p1_title": "ਸੱਚੀ ਔਫਲਾਈਨ ਪ੍ਰਭੂਸੱਤਾ",
        "p1_desc": "ਪੂਰੀ ਨਿੱਜਤਾ ਇੱਕ ਬੁਨਿਆਦੀ ਨਿਯਮ ਹੈ। Nudge ਚੱਲਦੇ ਸਮੇਂ ਕੋਈ ਇੰਟਰਨੈੱਟ ਸੰਪਰਕ ਨਹੀਂ ਕਰਦਾ।",
        "p2_title": "ਸ਼ਾਂਤ ਆਨ-ਡਿਵਾਈਸ AI ਸਾਥੀ",
        "p2_desc": "AI ਮਨੁੱਖੀ ਆਤਮ-ਚਿੰਤਨ ਦੀ ਸੇਵਾ ਕਰਦਾ ਹੈ ਅਤੇ ਤੁਹਾਡੇ ਕੰਪਿਊਟਰ 'ਤੇ ਹੀ ਚੱਲਦਾ ਹੈ।",
        "p3_title": "ਦੋਸ਼-ਮੁਕਤ ਹਮਦਰਦ ਅੰਕੜੇ",
        "p3_desc": "ਦਿਨ ਖੁੰਝਣ 'ਤੇ ਕੋਈ ਲਾਲ ਨਿਸ਼ਾਨ ਨਹੀਂ: Nudge ਲਿਖਣਾ ਮੁੜ ਸ਼ੁਰੂ ਕਰਨ ਦਾ ਸੁਆਗਤ ਕਰਦਾ ਹੈ।"
    },
    "ml": {
        "name": "Nudge — ലോക്കൽ AI കൂട്ടുകാരനോടൊപ്പമുള്ള ഓഫ്‌ലൈൻ ജേണലും ഡയറിയും",
        "subtitle": "Windows-നായി ഉപകരണത്തിൽ പ്രവർത്തിക്കുന്ന AI ഉള്ള ഓഫ്‌ലൈൻ ഡയറി",
        "tagline": "നിങ്ങളുടെ ചിന്തകൾ നിങ്ങളുടെ സ്വന്തമാണ് — ക്ലൗഡിന്റേതല്ല.",
        "badge_offline": "100% ഓഫ്‌ലൈൻ സുരക്ഷിതം",
        "badge_ai": "ഓൺ-ഡിവൈസ് AI (ക്ലൗഡ് ഇല്ല)",
        "badge_markdown": "ശുദ്ധമായ Markdown (.md)",
        "badge_telemetry": "സീറോ ടെലിമെട്രി",
        "badge_hello": "Windows Hello ബയോമെട്രിക്സ്",
        "badge_price": "$0.99 ഒറ്റത്തവണ വാങ്ങൽ",
        "cta_store": "Microsoft Store-ൽ നിന്ന് നേടുക",
        "cta_trial": "15 ദിവസത്തെ സൗജന്യ ട്രയൽ ഡൗൺലോഡ് ചെയ്യുക",
        "cta_buy": "ഒരിക്കൽ വാങ്ങുക — $0.99 ആജീവനാന്തം",
        "cta_see": "ആർക്കിടെക്ചർ പരിശോധിക്കുക",
        "h_pillars": "Nudge-ന്റെ മൂന്ന് അചഞ്ചലമായ തൂണുകൾ",
        "p1_title": "യഥാർത്ഥ ഓഫ്‌ലൈൻ പരമാധികാരം",
        "p1_desc": "പൂർണ്ണ സ്വകാര്യത പ്രാഥമിക നിബന്ധനയാണ്. Nudge ഇന്റർനെറ്റ് ഉപയോഗിക്കുന്നതേയില്ല.",
        "p2_title": "ശാന്തനായ ഓൺ-ഡിവൈസ് AI കൂട്ടുകാരൻ",
        "p2_desc": "AI നിങ്ങളുടെ ആത്മപരിശോധനയെ സഹായിക്കുന്നു, 100% നിങ്ങളുടെ ഉപകരണത്തിൽ പ്രവർത്തിക്കുന്നു.",
        "p3_title": "കുറ്റബോധമില്ലാത്ത സഹാനുഭൂതി നിറഞ്ഞ കണക്കുകൾ",
        "p3_desc": "ദിവസങ്ങൾ നഷ്ടപ്പെട്ടാലും ചുവപ്പ് മുന്നറിയിപ്പുകളില്ല: Nudge എഴുത്തിലേക്ക് തിരിച്ചുവരവിനെ സ്വാഗതം ചെയ്യുന്നു."
    },
    "kn": {
        "name": "Nudge — ಸ್ಥಳೀಯ AI ಒಡನಾಡಿಯೊಂದಿಗೆ ಆಫ್‌ಲೈನ್ ಜರ್ನಲ್ ಮತ್ತು ಡೈರಿ",
        "subtitle": "Windows ಗಾಗಿ ಆನ್-ಡಿವೈಸ್ AI ಹೊಂದಿರುವ ಸಂಪೂರ್ಣ ಆಫ್‌ಲೈನ್ ಡೈರಿ",
        "tagline": "ನಿಮ್ಮ ಆಲೋಚನೆಗಳು ನಿಮ್ಮ ಸ್ವಂತದ್ದು — ಕ್ಲೌಡ್‌ನದ್ದಲ್ಲ.",
        "badge_offline": "100% ಆಫ್‌ಲೈನ್ ಭದ್ರತೆ",
        "badge_ai": "ಆನ್-ಡಿವೈಸ್ AI (ಕ್ಲೌಡ್ ರಹಿತ)",
        "badge_markdown": "ಶುದ್ಧ Markdown (.md)",
        "badge_telemetry": "ಶೂನ್ಯ ಟೆಲಿಮೆಟ್ರಿ",
        "badge_hello": "Windows Hello ಬಯೋಮೆಟ್ರಿಕ್ಸ್",
        "badge_price": "$0.99 ಏಕಕಾಲಿಕ ಖರೀದಿ",
        "cta_store": "Microsoft Store ನಲ್ಲಿ ಪಡೆಯಿರಿ",
        "cta_trial": "15 ದಿನಗಳ ಉಚಿತ ಪ್ರಯೋಗವನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
        "cta_buy": "ಒಮ್ಮೆ ಖರೀದಿಸಿ — $0.99 ಜೀವಿತಾವಧಿ",
        "cta_see": "ವಿನ್ಯಾಸ ಮತ್ತು ತಾಂತ್ರಿಕ ವಿವರಗಳನ್ನು ನೋಡಿ",
        "h_pillars": "Nudge ನ ಮೂರು ಅಚಲ ಸ್ತಂಭಗಳು",
        "p1_title": "ನಿಜವಾದ ಆಫ್‌ಲೈನ್ ಸಾರ್ವಭೌಮತ್ವ",
        "p1_desc": "ಸಂಪೂರ್ಣ ಗೌಪ್ಯತೆ ಮೂಲ ನಿಯಮವಾಗಿದೆ. Nudge ಯಾವುದೇ ನೆಟ್‌ವರ್ಕ್ ಕರೆಗಳನ್ನು ಮಾಡುವುದಿಲ್ಲ.",
        "p2_title": "ಶಾಂತ ಆನ್-ಡಿವೈಸ್ AI ಒಡನಾಡಿ",
        "p2_desc": "AI ಮನುಷ್ಯನ ಆತ್ಮಾವಲೋಕನಕ್ಕೆ ಸಹಾಯ ಮಾಡುತ್ತದೆ ಮತ್ತು ನಿಮ್ಮ ಸಾಧನದಲ್ಲೇ ಚಲಿಸುತ್ತದೆ.",
        "p3_title": "ಅಪರಾಧಭಾವವಿಲ್ಲದ ಸಹಾನುಭೂತಿಯ ಅಂಕಿಅಂಶಗಳು",
        "p3_desc": "ದಿನ ಬಿಟ್ಟುಹೋದರೆ ಕೆಂಪು ಎಚ್ಚರಿಕೆಗಳಿಲ್ಲ: Nudge ಬರವಣಿಗೆಗೆ ಮರಳುವುವನ್ನು ಪ್ರೋತ್ಸಾಹಿಸುತ್ತದೆ."
    },
    "jv": {
        "name": "Nudge — Jurnal & Buku Harian Offline kanthi AI Lokal",
        "subtitle": "Buku harian offline kanggo Windows kanthi AI ing piranti",
        "tagline": "Pikiran sampeyan kagungane sampeyan — dudu kagungane cloud.",
        "badge_offline": "100% Offline / Aman",
        "badge_ai": "AI ing Piranti (Tanpa Cloud)",
        "badge_markdown": "Markdown Murni (.md)",
        "badge_telemetry": "Nol Telemetri",
        "badge_hello": "Biometrik Windows Hello",
        "badge_price": "$0.99 Tuku Sepisan",
        "cta_store": "Entuk ing Microsoft Store",
        "cta_trial": "Undhuh Uji Coba Gratis 15 Dina",
        "cta_buy": "Tuku Sepisan — $0.99 Selawase",
        "cta_see": "Deleng Arsitektur & Spesifikasi",
        "h_pillars": "Telung Rukun Utama Nudge",
        "p1_title": "Kedaulatan Offline Sejati",
        "p1_desc": "Privasi total minangka paugeran baku. Nudge ora nate ngirim data liwat internet.",
        "p2_title": "Kanca AI ing Piranti sing Ayem",
        "p2_desc": "AI nulungi refleksi dhiri, lumaku kanthi 100% lokal ing piranti sampeyan.",
        "p3_title": "Cathetan Pangerten Tanpa Rasa Salah",
        "p3_desc": "Ora ana tandha abang sing ngukum: Nudge menehi dina toleransi kanggo nulung sampeyan."
    },
    "sw": {
        "name": "Nudge — Shajara na Jarida ya Nje ya Mtandao yenye AI ya Kwenye Kifaa",
        "subtitle": "Shajara ya Windows isiyounganishwa na mtandao yenye AI ya ndani",
        "tagline": "Mawazo yako ni yako mwenyewe — si ya wingu.",
        "badge_offline": "100% Nje ya Mtandao",
        "badge_ai": "AI ya Kwenye Kifaa (Bila Wingu)",
        "badge_markdown": "Faili za Markdown (.md)",
        "badge_telemetry": "Bila Ufuatiliaji Wowote",
        "badge_hello": "Ulinzi wa Windows Hello",
        "badge_price": "$0.99 Malipo Moja",
        "cta_store": "Pata kwenye Microsoft Store",
        "cta_trial": "Pakua Jaribio la Siku 15 Bure",
        "cta_buy": "Nunua Mara Moja — $0.99 Maisha Yote",
        "cta_see": "Tazama Muundo na Maelezo",
        "h_pillars": "Nguzo Tatu Imara za Nudge",
        "p1_title": "Uhuru Kamili wa Nje ya Mtandao",
        "p1_desc": "Faragha kamili ni msingi mkuu wa muundo. Nudge haitumi data yoyote mtandaoni.",
        "p2_title": "Msaidizi wa AI wa Ndani ya Kifaa",
        "p2_desc": "AI inasaidia tafakuri yako binafsi na inafanya kazi 100% ndani ya kompyuta yako.",
        "p3_title": "Vipimo vya Huruma Visivyo na Hatia",
        "p3_desc": "Hakuna alama nyekundu za adhabu unapokosa siku: Nudge inakupa siku za msamaha."
    },
    "ha": {
        "name": "Nudge — Littafin Rubutun Kullum Ba Tare da Yanar Gizo ba tare da Abokin AI",
        "subtitle": "Littafin rubutu na Windows wanda baya bukatar intanet tare da AI a cikin na'ura",
        "tagline": "Tunaninka naka ne — ba na gajimare ba.",
        "badge_offline": "100% Ba tare da Intanet ba",
        "badge_ai": "AI a Cikin Na'ura (Babu Cloud)",
        "badge_markdown": "Rubutun Markdown (.md)",
        "badge_telemetry": "Babu Bibiya ko Kadan",
        "badge_hello": "Kariyar Windows Hello",
        "badge_price": "$0.99 Sayi Sau Daya",
        "cta_store": "Samu a Microsoft Store",
        "cta_trial": "Sauke Gwajin Kwanaki 15 Kyauta",
        "cta_buy": "Sayi Sau Daya — $0.99 Har Abada",
        "cta_see": "Duba Tsarin Fasaha",
        "h_pillars": "Rukunai Uku Masu Karfi na Nudge",
        "p1_title": "Cikakken Ikon Ba Tare da Yanar Gizo ba",
        "p1_desc": "Sirri na gaskiya shine ginshikin Nudge. Baya tura ko karbar bayani ta intanet.",
        "p2_title": "Abokin AI Mai Sauki a Na'ura",
        "p2_desc": "Fasahar AI tana aiki a cikin kwamfutarka kadai don taimaka maka tunani.",
        "p3_title": "Kididdiga Mai Tausayi Ba Tare da Laifi ba",
        "p3_desc": "Babu lambobi jajaye don tsoratarwa idan ka rasa rana: Nudge yana karfafa maka gwiwa."
    },
    "yo": {
        "name": "Nudge — Iwe Akọsilẹ Laisi Ayelujara pẹlu Oluranlọwọ AI Agbegbe",
        "subtitle": "Iwe akọsilẹ Windows laisi intanẹẹti pẹlu AI lori ẹrọ",
        "tagline": "Awọn ero rẹ jẹ tirẹ — kii ṣe ti awọsanma.",
        "badge_offline": "100% Laisi Ayelujara",
        "badge_ai": "AI Lori Ẹrọ (Ko si Awọsanma)",
        "badge_markdown": "Markdown Otitọ (.md)",
        "badge_telemetry": "Ko si Titọpa Rara",
        "badge_hello": "Aabo Windows Hello",
        "badge_price": "$0.99 Ra Lẹkan",
        "cta_store": "Gba lori Microsoft Store",
        "cta_trial": "Gba Idanwo Ọfẹ Ọjọ 15",
        "cta_buy": "Ra Lẹkan — $0.99 Fun Igbesi Aye",
        "cta_see": "Wo Eto ati Awọn Alaye",
        "h_pillars": "Awọn Origun Mẹta Pataki ti Nudge",
        "p1_title": "Agbara Laisi Ayelujara Todaju",
        "p1_desc": "Aṣiri pipe jẹ dandan. Nudge ko ni firanṣẹ tabi gba data lori intanẹẹti.",
        "p2_title": "Oluranlọwọ AI ti o dakẹ lori Ẹrọ",
        "p2_desc": "AI wa fun ifarabalẹ ara ẹni, o n ṣiṣẹ 100% lori kọnputa rẹ nikan.",
        "p3_title": "Awọn Iwọn Aanu Laisi Ẹbi",
        "p3_desc": "Ko si awọn aami pupa ti o n da lẹbi: Nudge n fun ọ ni awọn ọjọ aanu lati tẹsiwaju."
    },
    "my": {
        "name": "Nudge — အော့ဖ်လိုင်း ဒိုင်ယာရီနှင့် စက်တွင်း AI အဖော်မွန်",
        "subtitle": "အင်တာနက်မလိုသော Windows အတွက် ဒိုင်ယာရီနှင့် စက်တွင်း AI",
        "tagline": "သင့်အတွေးများသည် သင့်ကိုယ်ပိုင်ဖြစ်သည် — ကလောက်ဒ်မဟုတ်ပါ။",
        "badge_offline": "၁၀၀% အော့ဖ်လိုင်း အပြည့်အဝ",
        "badge_ai": "စက်တွင်း AI (ကလောက်ဒ်လုံးဝမပါ)",
        "badge_markdown": "ရိုးရှင်းသော Markdown (.md)",
        "badge_telemetry": "အချက်အလက်ခြေရာခံမှု လုံးဝမရှိ",
        "badge_hello": "Windows Hello ဇီဝလုံခြုံရေး",
        "badge_price": "$0.99 တစ်ခါဝယ်ယူရုံဖြင့်",
        "cta_store": "Microsoft Store တွင် ရယူပါ",
        "cta_trial": "၁၅ ရက် အခမဲ့ စမ်းသပ်သုံးစွဲရန် ဒေါင်းလုဒ်လုပ်ပါ",
        "cta_buy": "တစ်ခါဝယ် အပြီးပိုင် — $0.99",
        "cta_see": "နည်းပညာဖွဲ့စည်းပုံနှင့် အသေးစိတ်ကြည့်ရန်",
        "h_pillars": "Nudge ၏ မပြိုလဲနိုင်သော မဏ္ဍိုင်ကြီး ၃ ရပ်",
        "p1_title": "စစ်မှန်သော အော့ဖ်လိုင်း ပိုင်စိုးမှု",
        "p1_desc": "လုံးဝလုံခြုံမှုသည် အဓိကစည်းမျဉ်းဖြစ်ပြီး Nudge သည် အင်တာနက်အသုံးပြုမှု လုံးဝမရှိပါ။",
        "p2_title": "တိတ်ဆိတ်ငြိမ်သက်သော စက်တွင်း AI အဖော်",
        "p2_desc": "AI သည် လူသားတို့၏ အတွေးစများကို ကူညီပေးပြီး သင့်ကွန်ပျူတာပေါ်တွင်သာ အလုပ်လုပ်သည်။",
        "p3_title": "အပြစ်တင်ခြင်းကင်းသော မေတ္တာရှေ့ထား စာရင်းအင်းများ",
        "p3_desc": "ရက်ပျက်ကွက်သော်လည်း အနီရောင်သတိပေးချက်များမပါရှိဘဲ ပြန်လည်ရေးသားမှုကို ကြိုဆိုသည်။"
    },
    "am": {
        "name": "Nudge — ከመስመር ውጭ የግል ማስታወሻ እና የውስጥ AI አጋዥ",
        "subtitle": "ለዊንዶውስ የተዘጋጀ ከመስመር ውጭ ማስታወሻ እና በኮምፒውተር ላይ የሚሰራ AI",
        "tagline": "ሐሳቦችዎ የራስዎ ናቸው — የደመና አይደሉም።",
        "badge_offline": "100% ከመስመር ውጭ የሚሰራ",
        "badge_ai": "በመሳሪያው ላይ ያለ AI (ያለ ደመና)",
        "badge_markdown": "ንጹህ Markdown (.md) ፋይሎች",
        "badge_telemetry": "ምንም አይነት መረጃ መሰብሰብ የለም",
        "badge_hello": "የWindows Hello ጥበቃ",
        "badge_price": "$0.99 የአንድ ጊዜ ግዢ",
        "cta_store": "ከMicrosoft Store ያግኙ",
        "cta_trial": "የ15 ቀን ነጻ የሙከራ ጊዜ ያውርዱ",
        "cta_buy": "አንዴ ይግዙ — $0.99 ለዘላለም",
        "cta_see": "የአሰራር እና ቴክኒካዊ ዝርዝሮችን ይመልከቱ",
        "h_pillars": "የNudge ሶስቱ ጽኑ ምሰሶዎች",
        "p1_title": "እውነተኛ ከመስመር ውጭ ሉዓلاዊነት",
        "p1_desc": "ሙሉ ግላዊነት የማይጣስ መርህ ነው። Nudge ምንም አይነት የኢንተርኔት ግንኙነት አያደርግም።",
        "p2_title": "ጸጥተኛ የመሳሪያው ውስጥ AI አጋዥ",
        "p2_desc": "AI የራስን ውስጣዊ ሁኔታ ለማሰላሰል የሚረዳ ሆኖ በኮምፒውተርዎ ላይ ብቻ 100% ይሰራል::",
        "p3_title": "የጥፋተኝነት ስሜት የሌለበት አዛኝ ስታቲስቲክስ",
        "p3_desc": "ቀን ቢዘነጉ የቀይ ማስጠንቀቂያ ቁጥሮች የሉም፤ Nudge የመመለስ እድልዎን ያበረታታል።"
    },
    "kk": {
        "name": "Nudge — Жергілікті ЖИ серіктесі бар дербес офлайн күнделік",
        "subtitle": "Windows-қа арналған құрылғыдағы жасанды интеллектісі бар офлайн күнделік",
        "tagline": "Ойларыңыз тек өзіңізге тиесілі — бұлтқа емес.",
        "badge_offline": "100% Офлайн / Қауіпсіз",
        "badge_ai": "Құрылғыдағы ЖИ (Бұлтсыз)",
        "badge_markdown": "Таза Markdown (.md)",
        "badge_telemetry": "Нөлдік телеметрия",
        "badge_hello": "Windows Hello биометриясы",
        "badge_price": "$0.99 Бір реттік сатып алу",
        "cta_store": "Microsoft Store дүкенінен алу",
        "cta_trial": "15 күндік тегін нұсқаны жүктеп алу",
        "cta_buy": "Бір рет сатып алу — $0.99 өмірлік",
        "cta_see": "Сәулеті мен техникалық сипаттамаларын көру",
        "h_pillars": "Nudge-тің үш мызғымас тірегі",
        "p1_title": "Шынайы офлайн дербестік",
        "p1_desc": "Толық құпиялылық — негізгі талап. Nudge жұмыс барысында желіге ешқандай сұраныс жібермейді.",
        "p2_title": "Құрылғыдағы сабырлы ЖИ серіктес",
        "p2_desc": "ЖИ адамның өзін-өзі түсінуіне қызмет етеді. Модельдер тікелей дербес компьютеріңізде жұмыс істейді.",
        "p3_title": "Кінә сезімін тудырмайтын жанашыр көрсеткіштер",
        "p3_desc": "Қызыл айыппұл белгілері жоқ: Nudge жазуды жалғастыру үшін жеңілдік күндерін ұсынады."
    },
    "sk": {
        "name": "Nudge — Offline denník a zápisník s lokálnym AI spoločníkom",
        "subtitle": "Offline denník pre Windows s umelou inteligenciou v zariadení",
        "tagline": "Vaše myšlienky patria vám — nie cloudu.",
        "badge_offline": "100% Offline / Air-Gapped",
        "badge_ai": "Lokálna AI (Nulový cloud)",
        "badge_markdown": "Čistý Markdown (.md)",
        "badge_telemetry": "Nulová telemetria",
        "badge_hello": "Windows Hello biometria",
        "badge_price": "$0.99 Jednorazový nákup",
        "cta_store": "Získať v Microsoft Store",
        "cta_trial": "Stiahnuť 15-dňovú bezplatnú skúšobnú verziu",
        "cta_buy": "Kúpiť raz — $0.99 na celý život",
        "cta_see": "Preskúmať architektúru a špecifikácie",
        "h_pillars": "Tri nemenné piliere Nudge",
        "p1_title": "Skutočná offline suverenita",
        "p1_desc": "Úplné súkromie je architektonické pravidlo. Nudge nevykonáva žiadne sieťové volania.",
        "p2_title": "Tichý lokálny AI spoločník",
        "p2_desc": "AI má slúžiť ľudskej introspekcii. Modely bežia priamo na vašom procesore alebo NPU.",
        "p3_title": "Láskavé metriky bez pocitu viny",
        "p3_desc": "Žiadne červené sankčné čísla: Nudge ponúka dni tolerancie a víta váš návrat k písaniu."
    },
    "ca": {
        "name": "Nudge — Diari i Journal Offline amb Company d'IA Local",
        "subtitle": "Diari offline per a Windows amb IA al propi dispositiu",
        "tagline": "Els teus pensaments et pertanyen a tu — no al núvol.",
        "badge_offline": "100% Offline / Air-Gapped",
        "badge_ai": "IA al Dispositiu (Zero Núvol)",
        "badge_markdown": "Markdown Pur (.md)",
        "badge_telemetry": "Zero Telemetria",
        "badge_hello": "Biometria Windows Hello",
        "badge_price": "0,99 $ Pagament Únic",
        "cta_store": "Aconsegueix-lo a Microsoft Store",
        "cta_trial": "Descarrega la prova gratuïta de 15 dies",
        "cta_buy": "Compra una vegada — 0,99 $ per sempre",
        "cta_see": "Explora l'arquitectura i especificacions",
        "h_pillars": "Els tres pilars inviolables de Nudge",
        "p1_title": "Autèntica sobirania offline",
        "p1_desc": "La privacitat absoluta és un invariant arquitectònic. Nudge no fa cap crida de xarxa.",
        "p2_title": "Company d'IA local i discret",
        "p2_desc": "La intel·ligència artificial ha de servir la introspecció humana. Els models s'executen al teu dispositiu.",
        "p3_title": "Mètriques compassives sense culpa",
        "p3_desc": "Sense números vermells punitius: Nudge ofereix dies de gràcia i celebra el retorn a l'escriptura."
    }
}

updated_count = 0
for code, data in EXT.items():
    if code in L:
        target = L[code]
        for k, v in data.items():
            if not k.startswith("p"):
                target[k] = v
        if "p1_title" in data:
            target["pillars"] = [
                {"num": "1", "icon": "bi-shield-check", "title": data["p1_title"], "desc": data["p1_desc"]},
                {"num": "2", "icon": "bi-cpu", "title": data["p2_title"], "desc": data["p2_desc"]},
                {"num": "3", "icon": "bi-heart-pulse", "title": data["p3_title"], "desc": data["p3_desc"]}
            ]
        updated_count += 1

with open(STRINGS_PATH, "w", encoding="utf-8") as f:
    json.dump(L, f, ensure_ascii=False, indent=1)

print(f"Successfully enhanced {updated_count} locales in {STRINGS_PATH}")
